### PR TITLE
bump: 1.17 compatibility 

### PR DESCRIPTION
**Pull request by 5HT2**
Hi, I've worked out most of the issues with bumping this project to `1.17`. Unfortunately I'm stuck with another error that I'm unable to resolve, I'm hoping to work through this and get the pull merged, or at the very least have the pull be useful for someone else who's bumping it to `1.17`.

```
hydrogen-fabric ❯ ./gradlew build

> Configure project :
Fabric Loom: 0.8.17
Using project based jar storage
:remapping 2 mods (TinyRemapper, intermediary -> named)

unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)
unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)

> Configure project :
:remapping 1 mods (TinyRemapper, intermediary -> named)
:remapping sources

> Task :compileJava
warning: Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '16'
/home/liv/projects/hydrogen-fabric/src/main/java/me/jellysquid/mods/hydrogen/mixin/chunk/MixinBiomeArray.java:37: warning: Cannot find target method for @Inject in net.minecraft.world.biome.source.BiomeArray
@Inject(method = "<init>(Lnet/minecraft/util/collection/IndexedIterable;Lnet/minecraft/util/math/ChunkPos;Lnet/minecraft/world/biome/source/BiomeSource;[I)V", at = @At("RETURN"))
^
/home/liv/projects/hydrogen-fabric/src/main/java/me/jellysquid/mods/hydrogen/mixin/chunk/MixinBiomeArray.java:42: warning: Cannot find target method for @Inject in net.minecraft.world.biome.source.BiomeArray
@Inject(method = "<init>(Lnet/minecraft/util/collection/IndexedIterable;Lnet/minecraft/util/math/ChunkPos;Lnet/minecraft/world/biome/source/BiomeSource;)V", at = @At("RETURN"))
^
/home/liv/projects/hydrogen-fabric/src/main/java/me/jellysquid/mods/hydrogen/mixin/chunk/MixinBiomeArray.java:47: warning: Cannot find target method for @Inject in net.minecraft.world.biome.source.BiomeArray
@Inject(method = "<init>(Lnet/minecraft/util/collection/IndexedIterable;[Lnet/minecraft/world/biome/Biome;)V", at = @At("RETURN"))
^
/home/liv/projects/hydrogen-fabric/src/main/java/me/jellysquid/mods/hydrogen/mixin/chunk/MixinBiomeArray.java:53: warning: Cannot find target method for @Inject in net.minecraft.world.biome.source.BiomeArray
@Inject(method = "<init>(Lnet/minecraft/util/collection/IndexedIterable;[I)V", at = @At("RETURN"))
^
warning: Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '16'
/home/liv/projects/hydrogen-fabric/src/main/java/me/jellysquid/mods/hydrogen/mixin/client/model/json/MixinModelOverride.java:19: warning: Cannot find target for @Shadow field in net.minecraft.client.render.model.json.ModelOverride
@Shadow
^
/home/liv/projects/hydrogen-fabric/src/main/java/me/jellysquid/mods/hydrogen/mixin/client/model/json/MixinModelOverrideList.java:22: warning: Cannot find target for @Shadowfield in net.minecraft.client.render.model.json.ModelOverrideList
@Shadow
^
/home/liv/projects/hydrogen-fabric/src/main/java/me/jellysquid/mods/hydrogen/mixin/client/model/json/MixinModelOverrideList.java:27: warning: Cannot find target for @Shadowfield in net.minecraft.client.render.model.json.ModelOverrideList
@Shadow
^
/home/liv/projects/hydrogen-fabric/src/main/java/me/jellysquid/mods/hydrogen/mixin/chunk/MixinChunkSerializer.java:31: warning: Cannot find target for @Shadow method in net.minecraft.world.ChunkSerializer
@Shadow
^
/home/liv/projects/hydrogen-fabric/src/main/java/me/jellysquid/mods/hydrogen/mixin/chunk/MixinBiomeArray.java:26: warning: Cannot find target for @Shadow field in net.minecraft.world.biome.source.BiomeArray
@Shadow
^
/home/liv/projects/hydrogen-fabric/src/main/java/me/jellysquid/mods/hydrogen/mixin/nbt/MixinCompoundTag.java:20: warning: Cannot find target for @Shadow field in net.minecraft.nbt.NbtCompound
@Shadow
^
/home/liv/projects/hydrogen-fabric/src/main/java/me/jellysquid/mods/hydrogen/mixin/client/model/json/MixinSimpleMultipartModelSelector.java:39: warning: @Overwrite is missing an @reason tag
public Predicate<BlockState> getPredicate(StateManager<Block, BlockState> stateManager) {
^
/home/liv/projects/hydrogen-fabric/src/main/java/me/jellysquid/mods/hydrogen/mixin/client/model/MixinWeightedBakedModel.java:21: error: cannot find symbol
private List<WeightedBakedModel.Entry> models;
^
symbol:   class Entry
location: class WeightedBakedModel
1 error
13 warnings

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug optionto get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 23s
1 actionable task: 1 executed
```

### CODE REVIEW

**Comment by Leo40Git** [comment]
The reason it doesn't work is because Hydrogen uses some hacks to replace Guava collections with optimized ones.

These hacks break on Java 16 (which is required for Minecraft 1.17). #14 and #21 already exist to fix this.

(also apparently one of your classes didn't get remapped properly, check the `MixinWeightedBakedModel` class)

**Comment by 5HT2** [comment]
Good to know! I'll rebase my pull request onto the main branch once those pull requests get merged, along with fixing the mappings. (Feel free to bump or @ me here if I forget to check)

**Comment by jellysquid3** [comment]
I took a shot at this problem today, but there was some additional work needed with patches that weren't appearing because of the Java 16 issues. There is now a mostly-complete port [here](https://github.com/CaffeineMC/hydrogen-fabric/tree/1.17.x), though I appreciate your work here and apologize for stepping on this PR.

**Comment by 5HT2** [comment]
Thank you! I appreciate the response

**Pull request closed without merging**
